name: Node Continuous Integration
on:
  pull_request:
    branches: [master]

jobs:
  test_verification:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: "VERCEL_TOKEN"
      VERCEL_ORGID: ${{ secrets.VERCEL_ORGID }}
      VERCEL_PROJECTID: ${{ secrets.VERCEL_PROJECTID }}
      TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm ci
        - run: echo "Installation Done"
        - run: npm run test
        - run: echo "Verification Done"

  deploy:
    needs: test_verification
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - run: echo "DEPLOYMENT SUCCESSFUL"
      # - uses: actions/checkout@v2
      # - run: npm install --global vercel@latest
      # - run: vercel deploy --token="VERCEL_TOKEN"
