name: GitHub Actions Demo
on:
 push:
  branches: [dev]
 pull_request:
  branches: [dev]
jobs:
 runs-on: ubuntu-latest
 example_matrix:
  strategy:
   matrix:
    version: [10, 12, 14]
  steps:
   - uses: actions/setup-node@v3
     with:
      node-version: ${{ matrix.version }}
   - run: ls ${{ github.workspace }}
