name: GitHub Actions Demo
on:
 push:
  branches: [dev]
 pull_request:
  branches: [dev]
jobs:
 normal_ci:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - name: Run normal CI
   - run: npm i
   - run: npm install

 pull_request_ci:
  runs-on: ubuntu-latest
  if: ${{ github.event_name == 'pull_request' }}
  steps:
   - uses: actions/checkout@v3
   - name: echo "hello world"
