name: Node Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: "VERCEL_TOKEN"
      VERCEL_ORGID: ${{ secrets.VERCEL_ORGID }}
      VERCEL_PROJECTID: ${{ secrets.VERCEL_PROJECTID }}
      TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - run: echo "bonjour je suis le test"
        # - uses: actions/checkout@v2
        # - uses: actions/setup-node@v1
        #   with:
        #     node-version: ${{ matrix.node-version }}
        # - run: npm ci
        # - run: npm run test

  test_deploy:
    needs: test_pull_request
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token="VERCEL_TOKEN"
      - name: Build Project Artifacts
        run: vercel build --token="VERCEL_TOKEN"
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token="VERCEL_TOKEN"